DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS feed;
DROP TABLE IF EXISTS user_feed;
DROP TABLE IF EXISTS item;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE feed (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  link NVARCHAR NOT NULL,
  href TEXT NOT NULL
);

CREATE TABLE user_feed (
  user_id INTEGER NOT NULL,
  feed_id INTEGER NOT NULL
);

CREATE TABLE item (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  feed_id INTEGER,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  url NVARCHAR,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  guid TEXT,
  FOREIGN KEY (feed_id) REFERENCES feed (id)
);